version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: admin_panel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
   name: "pg"